### ISSUE TITLE
TypeError: API is not a constructor

### ISSUE THREAD

**Issue by jkutner** [mdlindsey/callofdutyapi#7]
When I follow the example in the README, and put this in my `index.js`:

```
import API from '@callofduty/api'

const CallOfDutyAPI = new API()
```

And I run:

```
$ npm i @callofduty/api
$ node index.js
```

I get the error:

```
TypeError: API is not a constructor
```

Am i missing a step?

## Environment

```
$ node -v
v16.1.0

$ npm -v
7.11.2
```

**Comment by mdlindsey** [comment]
This is a TypeScript config issue. Check your synthetic/default exports rules in your tsconfig.json

**Comment by yehezkel** [comment]
switch to this:
import {API} from '@callofduty/api'
