### ISSUE TITLE
request to login(https://s.activision.com/do_login?new_SiteId=activision) is stuck

### ISSUE THREAD

**Issue by guyng** [mdlindsey/callofdutyapi#9]
Hey, i'v tried multiple times from various of http clients and they all get stuck in the login phase
with the request to https://s.activision.com/do_login?new_SiteId=activision
the request is just continuous without stop. Also when i use the postman flow of callofdutyapi i have the same issue
Screenshot: https://prnt.sc/14ih0qh

Any idea what can be done to fix it?

Thanks
@mdlindsey @XanderHK

**Comment by iamPepouze** [comment]
Hello,

Same here, I'm having timeouts at login.
I tried with this library, your related Postman project and a C# wrapper.

Activision might have updated their API?

**Comment by mdlindsey** [comment]
Activision has made many changes to their API which has led us to offer this as a hosted service at https://callofdutyapi.com you can signup and create a new application to handle all your authentication (OAuth) and requests. Will close this issue when the npm package reflects the new hosted API, but do expect a major version change for that release.

**Comment by guyng** [comment]
> Activision has made many changes to their API which has led us to offer this as a hosted service at https://callofdutyapi.com you can signup and create a new application to handle all your authentication (OAuth) and requests. Will close this issue when the npm package reflects the new hosted API, but do expect a major version change for that release.

How soon do you think you'll release the new hosted service & updated npm package?

**Comment by mdlindsey** [comment]
> How soon do you think you'll release the new hosted service & updated npm package?

The hosted service is available for beta now at https://callofdutyapi.com - you can register your application and proceed with OAuth/Webhook flows. Postman collection is ready for the beta and the npm package updates will follow after the beta has matured into an official v1.

**Comment by v1ct0rv** [comment]
Hey Guys, any update on this?

**Comment by jackall3n** [comment]
Out of interest, what's the difference between this open source API and your hosted one? Are you planning on open sourcing the hosted API that contains the fix for the login timeout issue? 

It's probably not a good idea that people begin using your hosted version, as this means they'll be sharing their Activision password with you. I assume that you'll continue to use passwords in plain text, which means storing them in plain text as well. You're going to end up with a database of plain text passwords and therefore a target for anyone looking to gain those passwords. If you open source your hosted version people can continue to control how they store their plain text passwords.

**Comment by mdlindsey** [comment]
@jackall3n Our hosted services does not store passwords (or even emails) in any format whatsoever. The reasons for black-boxing the new login method are simple: 

1) We don't want to expose this to account thieves who have used this code maliciously in the past 
2) The auth tokens returned from Activision are far more powerful than a password (they persist beyond password reset) so in all honesty we don't trust other developers to handle these tokens with the sensitivity that the end users deserve

**Comment by jackall3n** [comment]
@mdlindsey so is your hosted service using an entirely different auth method? Without sharing the code are you able to share how that works? So that those of us who would like to implement it are able to.
